#goal definition
bool imu
bool odometry
---
#result definition
float64 imu_gz_biais_correction_value
float64 imu_gz_coef_correction_factor
float64 wheel_size_correction_factor
float64 wheel_interval_factor
---
#feedback
string current_step
float64 step_progress
